# Generated by Django 4.2.23 on 2025-07-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
